# This is a basic workflow to help you get started with Actions

name: Master-Deploy

# Controls when the action will run.
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Download Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Update with your python version
      - name: Install dependencies
        working-directory: "./src"
        run: |
          pip install poetry
          npm install
          npm install "./src"
          npm install fs-extra
          npm install aws-sdk
          npm install -g serverless
          serverless plugin install --name serverless-python-requirements
          serverless plugin install --name serverless-domain-manager
          rm -rf node_modules
          sls deploy -v -s prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
